name: kevin_flutter_core_platform_interface
description: A common platform interface for the kevin_flutter_core plugin.
repository: https://github.com/getkevin/kevin-flutter/tree/master/packages/kevin_flutter_core/kevin_flutter_core_platform_interface
homepage: https://developer.kevin.eu/mobile/
version: 1.0.4

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
