name: kevin_flutter_in_app_payments_ios
description: iOS implementation of the kevin_flutter_in_app_payments plugin.
repository: https://github.com/getkevin/kevin-flutter/tree/master/packages/kevin_flutter_in_app_payments/kevin_flutter_in_app_payments_ios
homepage: https://developer.kevin.eu/mobile/
version: 1.0.0

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  kevin_flutter_core: ^1.0.3
  kevin_flutter_in_app_payments_platform_interface: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

flutter:
  plugin:
    implements: kevin_flutter_in_app_payments
    platforms:
      ios:
        pluginClass: KevinFlutterInAppPaymentsPlugin
        dartPluginClass: KevinFlutterPaymentsIos

