name: kevin_flutter_example
description: kevin. Flutter SDK example app
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  domain:
    path: ./domain
  data:
    path: ./data
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  bloc_concurrency: ^0.2.0
  quiver: ^3.1.0
  collection: ^1.16.0
  dio: ^4.0.6
  fimber: ^0.6.1
  flutter_svg: ^1.1.5
  scroll_snap_list: ^0.9.1
  url_launcher: ^6.1.5
  modal_bottom_sheet: ^2.1.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

  # kevin. SDK plugins
  kevin_flutter_core:
    path: ../packages/kevin_flutter_core/kevin_flutter_core
  kevin_flutter_in_app_payments:
    path: ../packages/kevin_flutter_in_app_payments/kevin_flutter_in_app_payments

dependency_overrides:
  kevin_flutter_core:
    path: ../packages/kevin_flutter_core/kevin_flutter_core
  kevin_flutter_core_platform_interface:
    path: ../packages/kevin_flutter_core/kevin_flutter_core_platform_interface
  kevin_flutter_core_android:
    path: ../packages/kevin_flutter_core/kevin_flutter_core_android
  kevin_flutter_core_ios:
    path: ../packages/kevin_flutter_core/kevin_flutter_core_ios
  kevin_flutter_in_app_payments_platform_interface:
    path: ../packages/kevin_flutter_in_app_payments/kevin_flutter_in_app_payments_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - resources/icons/
    - resources/flags/

  fonts:
    - family: kevin_circular_std
      fonts:
        - asset: resources/fonts/kevin_circular_std_book.otf
          weight: 400
        - asset: resources/fonts/kevin_circular_std_medium.otf
          weight: 600
        - asset: resources/fonts/kevin_circular_std_bold.otf
          weight: 700

