name: kevin_flutter_example
description: Example ass using kevin. SDK flutter plugins
version: 0.0.1
homepage: https://github.com/getkevin/kevin-flutter/tree/master/packages/example
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  kevin_flutter_core:
    path: ../kevin_flutter_core
  kevin_flutter_in_app_payments:
    path: ../kevin_flutter_in_app_payments
  kevin_flutter_accounts:
    path: ../kevin_flutter_accounts

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
