name: kevin_flutter_accounts_android
description: Android implementation of the kevin_flutter_accounts plugin.
repository: https://github.com/getkevin/kevin-flutter/tree/master/packages/kevin_flutter_accounts/kevin_flutter_accounts_android
homepage: https://developer.kevin.eu/mobile/
version: 1.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  kevin_flutter_core: ^1.1.0
  kevin_flutter_accounts_platform_interface: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

flutter:
  plugin:
    implements: kevin_flutter_accounts
    platforms:
      android:
        package: eu.kevin.flutter.accounts
        pluginClass: KevinFlutterAccountsPlugin
        dartPluginClass: KevinFlutterAccountsAndroid
