name: kevin_flutter_accounts
description: Flutter plugin to communicate with kevin. accounts SDK.
homepage: https://github.com/getkevin/kevin-flutter/tree/master/packages/kevin_flutter_accounts/kevin_flutter_accounts
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  kevin_flutter_core:
    path: ../../kevin_flutter_core/kevin_flutter_core
  kevin_flutter_accounts_platform_interface:
    path: ../kevin_flutter_accounts_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

flutter:
  plugin:
    platforms:
      android:
        package: eu.kevin.flutter.accounts
        pluginClass: KevinFlutterAccountsPlugin
      ios:
        pluginClass: KevinFlutterAccountsPlugin
