name: kevin_flutter_accounts
description: Flutter plugin, used to easily communicate with kevin. account linking SDK.
repository: https://github.com/getkevin/kevin-flutter/tree/master/packages/kevin_flutter_accounts/kevin_flutter_accounts
homepage: https://developer.kevin.eu/mobile/
version: 1.2.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  kevin_flutter_core: ^1.2.0
  kevin_flutter_accounts_android: ^1.2.0
  kevin_flutter_accounts_ios: ^1.2.0
  kevin_flutter_accounts_platform_interface: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

flutter:
  plugin:
    platforms:
      android:
        default_package: kevin_flutter_accounts_android
      ios:
        default_package: kevin_flutter_accounts_ios
