name: kevin_flutter_core_ios
description: iOS implementation of the kevin_flutter_core plugin.
homepage: https://github.com/getkevin/kevin-flutter/tree/master/packages/kevin_flutter_core/kevin_flutter_core_ios
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  kevin_flutter_core_platform_interface:
    path: ../kevin_flutter_core_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

flutter:
  plugin:
    implements: kevin_flutter_core
    platforms:
      ios:
        pluginClass: KevinFlutterCorePlugin
        dartPluginClass: KevinFlutterCoreIos
