name: kevin_flutter_in_app_payments
description: Flutter plugin to communicate with kevin. in app payments SDK
version: 0.0.1
homepage: https://github.com/getkevin/kevin-flutter/tree/master/packages/kevin_flutter_in_app_payments
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  json_annotation: ^4.6.0
  kevin_flutter_core:
    path: ../kevin_flutter_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

flutter:
  plugin:
    platforms:
      android:
        package: eu.kevin.flutter.payments
        pluginClass: KevinFlutterPaymentsPlugin
      ios:
        pluginClass: KevinFlutterPaymentsPlugin
