name: kevin_flutter_core
description: Flutter plugin to communicate with kevin. SDK
version: 0.0.1
homepage: https://github.com/getkevin/kevin-flutter/tree/master/packages/kevin_flutter_core

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: eu.kevin.flutter.core
        pluginClass: KevinFlutterPlugin
      ios:
        pluginClass: KevinFlutterPlugin
