name: kevin_flutter_accounts_platform_interface
description: A common platform interface for the kevin_flutter_accounts plugin.
homepage: https://github.com/getkevin/kevin-flutter/tree/master/packages/kevin_flutter_accounts/kevin_flutter_accounts_platform_interface
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0
  kevin_flutter_core:
    path: ../../kevin_flutter_core/kevin_flutter_core

dev_dependencies:
  flutter_test:
    sdk: flutter