name: kevin_flutter_in_app_payments
description: Flutter plugin, used to easily communicate with kevin. in app payments SDK.
repository: https://github.com/getkevin/kevin-flutter/tree/master/packages/kevin_flutter_in_app_payments/kevin_flutter_in_app_payments
homepage: https://developer.kevin.eu/mobile/
version: 1.0.3

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  kevin_flutter_core: ^1.0.4
  kevin_flutter_in_app_payments_android: ^1.0.1
  kevin_flutter_in_app_payments_ios: ^1.0.2
  kevin_flutter_in_app_payments_platform_interface: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

flutter:
  plugin:
    platforms:
      android:
        default_package: kevin_flutter_in_app_payments_android
      ios:
        default_package: kevin_flutter_in_app_payments_ios
