name: kevin_flutter_core
description: Flutter plugin for kevin. SDK core, required by payments and account linking plugins.
repository: https://github.com/getkevin/kevin-flutter/tree/master/packages/kevin_flutter_core/kevin_flutter_core
homepage: https://developer.kevin.eu/mobile/
version: 1.0.2

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  kevin_flutter_core_android: ^1.0.2
  kevin_flutter_core_ios: ^1.0.2
  kevin_flutter_core_platform_interface: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

flutter:
  plugin:
    platforms:
      android:
        default_package: kevin_flutter_core_android
      ios:
        default_package: kevin_flutter_core_ios
